---
# Copyright 2018 widdix GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::LanguageExtensions'
Description: 'cfn-modules: SSH bastion'
# cfn-modules:implements(Bastion)
# TODO could be based on module asg-singleton-amazon-linux2
Parameters:
  VpcModule:
    Description: 'Stack name of vpc module.'
    Type: String
  AlertingModule:
    Description: 'Optional but recommended stack name of alerting module.'
    Type: String
    Default: ''
  HostedZoneModule:
    Description: 'Optional but recommended stack name of module implementing HostedZone.'
    Type: String
    Default: ''
  KeyName:
    Description: 'Optional key name of the Linux user ec2-user to establish a SSH connection to the EC2 instance.'
    Type: String
    Default: ''
  IAMUserSSHAccess:
    Description: 'Synchronize public keys of IAM users to enable personalized SSH access (https://github.com/widdix/aws-ec2-ssh)?'
    Type: String
    Default: false
    AllowedValues: [true, false]
  InstanceType:
    Description: 'The instance type for the EC2 instance.'
    Type: String
    Default: 't2.nano'
  LogGroupRetentionInDays:
    Description: 'Specifies the number of days you want to retain log events.'
    Type: Number
    Default: 14
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
  SubDomainNameWithDot:
    Description: 'Name that is used to create the DNS entry with trailing dot, e.g. §{SubDomainNameWithDot}§{HostedZoneName}. Leave blank for naked (or apex and bare) domain. Requires HostedZoneModule parameter!'
    Type: String
    Default: 'ssh.'
  LatestAmiId:
    Description: 'The latest amazon linux instance AMI for the region'
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-minimal-kernel-default-x86_64'
  AmiId:
    Description: 'A specific AMI ID to use for the launc template'
    Type: String
    Default: ''
  AllowedCidrIps:
    Description: 'A CSV of allowed IPV4 CIDRs that are allowed to connect to the bastion'
    Type: CommaDelimitedList
    Default: ''
Conditions:
  HasAlertingModule: !Not [!Equals [!Ref AlertingModule, '']]
  HasHostedZoneModule: !Not [!Equals [!Ref HostedZoneModule, '']]
  HasKeyName: !Not [!Equals [!Ref KeyName, '']]
  HasIAMUserSSHAccess: !Equals [!Ref IAMUserSSHAccess, 'true']
  HasSpecificAmiId: !Not [!Equals [!Ref AmiId, '']]
  # Use Fn::Join because Fn::Length will evaluate to 1 with an empty string in a CommaDelimitedList
  HasAllowedCidrIps: !Not [ !Equals [ Fn::Join: [ '', !Ref AllowedCidrIps ], '' ] ]
Resources:
  RecordSet:
    Condition: HasHostedZoneModule
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId:
        'Fn::ImportValue': !Sub '${HostedZoneModule}-Id'
      Name: !Sub
      - '${SubDomainNameWithDot}${HostedZoneName}'
      - SubDomainNameWithDot: !Ref SubDomainNameWithDot
        HostedZoneName:
          'Fn::ImportValue': !Sub '${HostedZoneModule}-Name'
      ResourceRecords:
      - !Ref ElasticIP
      TTL: 60
      Type: A
  ElasticIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      Domain: vpc
  LogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      RetentionInDays: !Ref LogGroupRetentionInDays
  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: !Ref 'AWS::StackName'
      VpcId:
        'Fn::ImportValue': !Sub '${VpcModule}-Id'
  'Fn::ForEach::SecurityGroupIngressRules':
    - CIDR
    - !Ref AllowedCidrIps
    - 'IngressRule&{CIDR}':
        Type: 'AWS::EC2::SecurityGroupIngress'
        Condition: HasAllowedCidrIps
        Properties:
          CidrIp: !Ref CIDR
          GroupId: !Ref SecurityGroup
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
  InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
      - !Ref Role
  Role:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: 'ec2.amazonaws.com'
          Action: 'sts:AssumeRole'
      Policies:
      - PolicyName: ec2
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: 'ec2:AssociateAddress'
            Resource: '*'
      - PolicyName: logs
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - 'logs:CreateLogGroup'
            - 'logs:CreateLogStream'
            - 'logs:PutLogEvents'
            - 'logs:DescribeLogStreams'
            Resource: !GetAtt 'LogGroup.Arn'
  PolicySshAccess:
    Type: 'AWS::IAM::Policy'
    Condition: HasIAMUserSSHAccess
    Properties:
      Roles:
      - !Ref Role
      PolicyName: 'ssh-access'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - 'iam:ListUsers'
          - 'iam:GetGroup'
          Resource: '*'
        - Effect: Allow
          Action:
          - 'iam:ListSSHPublicKeys'
          - 'iam:GetSSHPublicKey'
          Resource: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:user/*'
        - Effect: Allow
          Action: 'ec2:DescribeTags'
          Resource: '*'
  LaunchTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    Metadata:
      'AWS::CloudFormation::Init':
        configSets:
          default: !If [HasIAMUserSSHAccess, [cloudwatch, config], [cloudwatch, config]]
        cloudwatch:
          packages:
            yum:
              amazon-cloudwatch-agent: []
              rsyslog: []
          files:
            '/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json':
              # https://repost.aws/knowledge-center/ec2-linux-al2023-find-log-files
              content: !Sub |
                {
                  "logs": {
                    "logs_collected": {
                      "files": {
                        "collect_list": [
                          {
                            "file_path": "/var/log/messages",
                            "log_group_name": "${LogGroup}",
                            "log_stream_name": "{instance_id}/var/log/messages",
                            "timestamp_format": "%b %d %H:%M:%S"
                          },
                          {
                            "file_path": "/var/log/secure",
                            "log_group_name": "${LogGroup}",
                            "log_stream_name": "{instance_id}/var/log/secure",
                            "timestamp_format": "%b %d %H:%M:%S"
                          },
                          {
                            "file_path": "/var/log/cron",
                            "log_group_name": "${LogGroup}",
                            "log_stream_name": "{instance_id}/var/log/cron",
                            "timestamp_format": "%b %d %H:%M:%S"
                          },
                          {
                            "file_path": "/var/log/cloud-init.log",
                            "log_group_name": "${LogGroup}",
                            "log_stream_name": "{instance_id}/var/log/cloud-init.log",
                            "timestamp_format": "%b %d %H:%M:%S"
                          },
                          {
                            "file_path": "/var/log/cfn-init.log",
                            "log_group_name": "${LogGroup}",
                            "log_stream_name": "{instance_id}/var/log/cfn-init.log",
                            "timestamp_format": "%Y-%m-%d %H:%M:%S"
                          },
                          {
                            "file_path": "/var/log/cfn-hup.log",
                            "log_group_name": "${LogGroup}",
                            "log_stream_name": "{instance_id}/var/log/cfn-hup.log",
                            "timestamp_format": "%Y-%m-%d %H:%M:%S"
                          },
                          {
                            "file_path": "/var/log/cfn-init-cmd.log",
                            "log_group_name": "${LogGroup}",
                            "log_stream_name": "{instance_id}/var/log/cfn-init-cmd.log",
                            "timestamp_format": "%Y-%m-%d %H:%M:%S"
                          },
                          {
                            "file_path": "/var/log/cloud-init-output.log",
                            "log_group_name": "${LogGroup}",
                            "log_stream_name": "{instance_id}/var/log/cloud-init-output.log"
                          },
                          {
                            "file_path": "/var/log/dmesg",
                            "log_group_name": "${LogGroup}",
                            "log_stream_name": "{instance_id}/var/log/dmesg"
                          }
                        ]
                      }
                    },
                    "log_stream_name": "{instance_id}/var/log/"
                  }
                }
              mode: '000644'
              owner: root
              group: root
          services:
            systemd:
              rsyslog:
                enabled: true
                ensureRunning: true
              amazon-cloudwatch-agent:
                enabled: true
                ensureRunning: true
                packages:
                  yum:
                    - amazon-cloudwatch-agent
                files:
                  - '/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json'
        config:
          files:
            '/etc/cfn/cfn-hup.conf':
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
                interval=1
              mode: '000400'
              owner: root
              group: root
            '/etc/cfn/hooks.d/cfn-auto-reloader.conf':
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.LaunchTemplate.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init --verbose --stack=${AWS::StackName} --region=${AWS::Region} --resource=LaunchTemplate
                runas=root
          services:
            systemd:
              cfn-hup:
                enabled: true
                ensureRunning: true
                files:
                - '/etc/cfn/cfn-hup.conf'
                - '/etc/cfn/hooks.d/cfn-auto-reloader.conf'
    Properties:
      LaunchTemplateData:
        NetworkInterfaces:
        - DeviceIndex: '0'
          AssociatePublicIpAddress: true
          Groups:
          - !Ref SecurityGroup
        EbsOptimized: false
        IamInstanceProfile:
          Arn: !GetAtt InstanceProfile.Arn
        ImageId: !If [HasSpecificAmiId, !Ref AmiId, !Ref LatestAmiId]
        InstanceType: !Ref InstanceType
        KeyName: !If [HasKeyName, !Ref KeyName, !Ref 'AWS::NoValue']
        UserData:
          'Fn::Base64': !Sub |
            #!/bin/bash -ex
            sudo yum update -y
            sudo yum install -y aws-cfn-bootstrap
            trap '/opt/aws/bin/cfn-signal -e 1 --stack ${AWS::StackName} --resource AutoScalingGroup --region ${AWS::Region}' ERR
            TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600" -s)
            INSTANCEID=$(curl -s -m 6 --retry 3 --retry-delay 1 -H "X-aws-ec2-metadata-token: $TOKEN" -s "http://169.254.169.254/latest/meta-data/instance-id")
            aws --region ${AWS::Region} ec2 associate-address --instance-id $INSTANCEID --allocation-id ${ElasticIP.AllocationId}
            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource LaunchTemplate --region ${AWS::Region}
            /opt/aws/bin/cfn-signal -e 0 --stack ${AWS::StackName} --resource AutoScalingGroup --region ${AWS::Region}
  AutoScalingGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MaxSize: '1'
      MinSize: '1'
      Tags:
      - Key: Name
        Value: !Sub
        - 'SSH bastion ${CidrBlock}'
        - CidrBlock:
            'Fn::ImportValue': !Sub '${VpcModule}-CidrBlock'
        PropagateAtLaunch: true
      NotificationConfigurations: !If
      - HasAlertingModule
      - - NotificationTypes:
          - 'autoscaling:EC2_INSTANCE_LAUNCH_ERROR'
          - 'autoscaling:EC2_INSTANCE_TERMINATE_ERROR'
          TopicARN:
            'Fn::ImportValue': !Sub '${AlertingModule}-Arn'
      - []
      VPCZoneIdentifier: !Split
      - ','
      - 'Fn::ImportValue':
          !Sub '${VpcModule}-SubnetIdsPublic'
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: PT10M
    UpdatePolicy:
      AutoScalingRollingUpdate:
        PauseTime: PT10M
        SuspendProcesses:
        - HealthCheck
        - ReplaceUnhealthy
        - AZRebalance
        - AlarmNotification
        - ScheduledActions
        WaitOnResourceSignals: true
  AlarmCPUTooHigh:
    Condition: HasAlertingModule
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Average CPU utilization over last 10 minutes higher than 80%'
      Namespace: 'AWS/EC2'
      MetricName: CPUUtilization
      Statistic: Average
      Period: 600
      EvaluationPeriods: 1
      ComparisonOperator: GreaterThanThreshold
      Threshold: 80
      AlarmActions:
      - 'Fn::ImportValue': !Sub '${AlertingModule}-Arn'
      Dimensions:
      - Name: AutoScalingGroupName
        Value: !Ref AutoScalingGroup
Outputs:
  ModuleId:
    Value: 'ssh-bastion'
  ModuleVersion:
    Value: '1.5.0'
  StackName:
    Value: !Ref 'AWS::StackName'
  SecurityGroupId:
    Value: !Ref SecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-SecurityGroupId'
  PublicIpAddress:
    Value: !Ref ElasticIP
    Export:
      Name: !Sub '${AWS::StackName}-PublicIpAddress'
  HasAllowedCidrIps:
    Value: !If [ HasAllowedCidrIps, 'true', 'false']
